name: Build and Push to ACR
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        
    steps:
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Build and Push to ACR
        run: |
            docker build . --file Dockerfile --tag ${{ secrets.AZURE_URL }}/my-image-name:${{ github.sha }} 
            docker push ${{ secrets.AZURE_URL }}/my-image-name:${{ github.sha }} 

  deploy:
    name: Pull from ARC and deploy to ACI
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: 'Deploy Login'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        uses: 'azure/aci-deploy@v1'
        with:
         resource-group: ${{ secrets.RESOURCE_GROUP }}
         dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
         image: ${{ secrets.AZURE_URL }}/my-image-name:${{ github.sha }} 
         registry-login-server: ${{ secrets.AZURE_URL }}
         registry-username: ${{ secrets.ACR_USERNAME }}
         registry-password: ${{ secrets.ACR_PASSWORD }}
         name: testcicdcontainer
         location: 'east us'
         ports: '8080'
