name: Build and Push to ACR
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DATE: ${ (date +'%Y-%m-%d) }
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        
    steps:
        

      - name: Checkout
        uses: actions/checkout@v4

      - name: Output print
        run: echo "Date value from variable is $DATE --- Date value from direct is $(date +'%Y-%m-%d')"
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Build and Push to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
            #docker build . -t ${{ secrets.AZURE_URL }}/sampleapp:${{ github.sha }}
            docker build . --file Dockerfile --tag ${{ secrets.AZURE_URL }}/my-image-name:$(date +'%Y-%m-%d')
            docker push ${{ secrets.AZURE_URL }}/my-image-name:$(date +'%Y-%m-%d')
