name: Build and deploy to App Service
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-deploy-App:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        
    steps:
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Build and Push to ACR
        run: |
            docker build . --file Dockerfile --tag ${{ secrets.AZURE_URL }}/my-image-name:${{ github.sha }} 
            docker push ${{ secrets.AZURE_URL }}/my-image-name:${{ github.sha }} 

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'soumyatestcicd'
          images: 'soumyatestcicd.azurewebsites.net/soumyatestcicd:${{ github.sha }}'

      - name: Azure logout
        run: |
            az logout
