name: Replace Text Test

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "hello world"

      - name: checkout
        uses: actions/checkout@v3

      - name: Replace Tokens in env files
        uses: qetza/replacetokens-action@v1
        with:
          sources: '**/*.env.test'
          variables: '${{ ENV_VARS }}'
          tokenpattern: custom
          token-prefix: '__'
          token-suffix: '__'
